# https://github.com/marketplace/actions/npm-publish
name: Test vars
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setting environment variables with github org configuration variables
env:
  VITE_SUPABASE_URL: ${{vars.SUPABASE_URL}}
  VITE_SUPABASE_KEY: ${{vars.SUPABASE_KEY}}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "$VITE_SUPABASE_URL"
      - run: echo "$VITE_SUPABASE_KEY"
